baseURL = 'https://blog.qligier.ch/'
languageCode = 'en-us'
title = "Quentin's blog"
theme = 'qblog'
copyright = '© 2025 Quentin Ligier'

[params]
  description = 'The personal blog of Quentin Ligier'
  copyright = '© 2025 Quentin Ligier'
  [params.author]
    name = 'Quentin Ligier'

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html']

[sitemap]
  changeFreq = 'weekly'
  filename = 'sitemap.xml'
  priority = -1

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.x]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

pygmentsUseClasses = true
pygmentsCodefences = true
[markup.highlight]
  codeFences = true
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = true
  tabWidth = 4
  noClasses = false

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
    [markup.goldmark.renderer]
      unsafe = true
